Vagrant.configure("2") do |config|
  config.vm.box = "win2003x86"
  #doesn't exist yet - config.vm.box_url = "http://vagrant-windows.s3.amazonaws.com/win2003-x86-vbox4216-nocm.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider :virtualbox do |v|
    v.gui = true
  end

  config.vm.provider :vmware_fusion do |v|
    v.gui = true
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"

  # Configure base box parameters
  config.vm.guest = :windows

  # Max time to wait for the guest to shutdown
  config.windows.halt_timeout = 20

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # Port forward WinRM
  config.vm.network :forwarded_port, guest: 5985, host: 5985

  config.vm.synced_folder "~", "/home"
  # config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"
  # config.vm.synced_folder "puppet/box_modules", "/DOCUME~1/ALLUSE~1/APPLIC~1/PUPPET~1/puppet/etc/modules"

  # # This shell provisioner installs chocolatey, ruby, and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "shell/main.cmd"

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "puppet/modules"
    puppet.facter = {
      "domain" => "local",
      "kernel" => "windows",
      "operatingsystem" => "windows",
      "osfamily" => "windows",
    }
  end
end
