# Load upstream windows vagrant file with common settings
windows_vagrantfile = File.expand_path("../../VagrantWindows.rb", __FILE__)
load windows_vagrantfile if File.exist?(windows_vagrantfile)

Vagrant.configure("2") do |config|
  config.vm.box = "win2012r2x64"

  config.vm.provider :virtualbox do |v, override|
    override.vm.network :private_network, ip: "192.168.0.2"
  end

  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"
  config.vm.synced_folder "powershelldsc", "/powershelldsc"

  # These install chocolatey, ruby, and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "../shared/shell/PrepareWindows.ps1"
  #config.vm.provision :shell, :path => "../shared/shell/InstallNet4.ps1"
  config.vm.provision :shell, :path => "../shared/shell/InstallChocolatey.ps1"
  config.vm.provision :shell, :path => "../shared/shell/InstallPuppetFromMSI.ps1"
  #config.vm.provision :shell, :path => "../shared/shell/PreparePuppetProvisioner.ps1"
  config.vm.provision :shell, :path => "shell/SetupDSCComponents.ps1"
end
