# Load upstream windows vagrant file with common settings
windows_vagrantfile = File.expand_path("../../VagrantWindows.rb", __FILE__)
load windows_vagrantfile if File.exist?(windows_vagrantfile)

Vagrant.configure("2") do |config|
  config.vm.box = "win7x64pro"

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07dnlaNUp4aGdmOW8/"
  end

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07NE00OEQyYnoySDg/"
    override.vm.network :private_network, ip: "192.168.0.3"
  end

  #config.vm.network :forwarded_port, guest: 5985, host: 5987

  config.vm.synced_folder "~", "/home"
  config.vm.synced_folder "puppet/box_modules", "/ProgramData/PuppetLabs/puppet/etc/modules"

  # This shell provisioner installs chocolatey, ruby, and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "../shared/shell/main.cmd"

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "puppet/modules"
    puppet.facter = {
      "domain" => "local",
      "kernel" => "windows",
      "operatingsystem" => "windows",
      "osfamily" => "windows",
    }
  end
end
