install_pe = false
# Load upstream windows vagrant file with common settings
windows_vagrantfile = File.expand_path("../../VagrantWindows.rb", __FILE__)
load windows_vagrantfile if File.exist?(windows_vagrantfile)

if install_pe
  unless Vagrant.has_plugin?("vagrant-pe_build")
    raise 'vagrant-pe_build is not installed!'
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "win2008r2x64"

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07NmxkdmNma0xYb00/"
  end

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07cVB5SE5CWVFPZzg/"
    override.vm.network :private_network, ip: "192.168.0.8"
  end

  config.vm.synced_folder "puppet/modules", "/ProgramData/PuppetLabs/puppet/etc/modules"
  config.vm.synced_folder "puppet/modules", "/ProgramData/PuppetLabs/code/environments/production/modules"

  # These install chocolatey, ruby, and puppet. Also runs librarian-puppet.
  config.vm.provision :shell, :path => "../shared/shell/PrepareWindows.ps1"
  config.vm.provision :shell, :path => "../shared/shell/InstallChocolatey.ps1"


  if !install_pe
    config.vm.provision :shell, :path => "../shared/shell/InstallPuppetFromMSI.ps1"
  #config.vm.provision :shell, :path => "../shared/shell/PreparePuppetProvisioner.ps1"
    config.vm.provision :shell, :path => "../shared/shell/NotifyGuiAppsOfEnvironmentChanges.ps1"

    # Enable provisioning with Puppet stand alone.  Puppet manifests
    # are contained in a directory path relative to this Vagrantfile.
    config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file  = "empty.pp"
      puppet.module_path = "puppet/modules"
      puppet.facter = {
        "domain" => "local",
        "kernel" => "windows",
        "operatingsystem" => "windows",
        "osfamily" => "windows",
      }
    end
  else
    #NOTE: This isn't quite working due to main.cmd installing puppet already
    #PE install
    config.pe_build.version = '3.2.1'
    # if you don't have $PE_DOWNLOAD_ROOT defined,
    # you will want to comment this line out and
    # move to an older version of PE
    config.pe_build.download_root = "#{ENV['PE_DOWNLOAD_ROOT']}/:version"
    config.vm.provision :pe_bootstrap do |provisioner|
      provisioner.role = :agent
      provisioner.verbose = true
      provisioner.master = 'puppet'
    end
    config.vm.provision :pe_bootstrap
  end
end
