Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-12042-x64-nocm"

  config.vm.provider :virtualbox do |v, override|
    v.gui = false
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
  end

  config.vm.provider :vmware_fusion do |v, override|
    v.gui = false
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-svr-12042-x64-vf503-nocm.box"
  end

  config.vm.provision :shell, :path => "shell/PuppetInstall.sh"
  config.vm.provision :shell, :path => "shell/UpdateRuby.sh"

  # replace puppet installed with puppet dev:
  # sudo service puppetmaster stop
  # mv /usr/lib/ruby/site_ruby/1.8/puppet/ /usr/lib/ruby/site_ruby/1.8/puppet.old/
  # ln -s /code/puppetlabs/puppet/lib/puppet/ /usr/lib/ruby/site_ruby/1.8/puppet
  # sudo service puppetmaster start
end
