install_pe = true

if install_pe
  unless Vagrant.has_plugin?("vagrant-pe_build")
    raise 'vagrant-pe_build is not installed!'
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-12042-x64-nocm"

  config.vm.provider :virtualbox do |v, override|
    v.gui = false
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
    override.vm.network :private_network, ip: "192.168.0.4"
  end

  config.vm.provider :vmware_fusion do |v, override|
    v.gui = false
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-svr-12042-x64-vf503-nocm.box"
  end

  config.vm.provision :shell, :path => "shell/PrepareBox.sh"

  if install_pe
    #PE install - http://docs.puppetlabs.com/pe/latest/install_basic.html
    config.pe_build.version = '3.2.1'
    # if you don't have $PE_DOWNLOAD_ROOT defined,
    # you will want to comment this line out and
    # move to an older version of PE
    config.pe_build.download_root = "#{ENV['PE_DOWNLOAD_ROOT']}/:version"
    config.vm.provision :pe_bootstrap do |provisioner|
      provisioner.role = :master
      provisioner.verbose = true
    end

    config.vm.provision :pe_bootstrap
  else
    #config.vm.provision :shell, :path => "shell/UpdateRuby.sh"
    config.vm.provision :shell, :path => "shell/PuppetInstall.sh"
    config.vm.provision :shell, :path => "shell/ReplacePuppetWithDev.sh"
  end

  config.vm.provision :shell, :path => "shell/InstallModules.sh"
end
