Vagrant.configure("2") do |config|
  config.vm.box = "ubuntuserver1204-2-x64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
  #vmware fusion
  #config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-svr-12042-x64-vf503-nocm.box"

  config.vm.provider :virtualbox do |v|
    v.gui = true
  end

  config.vm.provider :vmware_fusion do |v|
    v.gui = true
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network :private_network, ip: "192.168.33.10"
end
