Vagrant.configure("2") do |config|
  config.vm.box = "centos-6.5-64-nocm"
  config.vm.box_url = "puppetlabs/centos-6.5-64-nocm"

  config.vm.provider :virtualbox do |v, override|
    override.vm.network :private_network, ip: "192.168.0.6"
  end

  config.vm.synced_folder "puppet/box_modules", "/etc/puppet/modules"
  config.vm.synced_folder "puppet/manifests", "/etc/puppet/manifests"

  config.vm.provision :shell, :path => "shell/PrepareRHEL6.sh"
  config.vm.provision :shell, :path => "shell/PuppetInstall.sh"
  #config.vm.provision :shell, :path => "shell/UpdateRuby.sh"
  #config.vm.provision :shell, :path => "shell/InstallUTF8Package.sh"
end
