Vagrant.configure("2") do |config|
  config.vm.box = "centos-64-x64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
  #vmware fusion
  #config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box"

  config.vm.provider :virtualbox do |v|
    # Don't boot with headless mode
    v.gui = true
  end

  config.vm.provider :vmware_fusion do |v|
    # Don't boot with headless mode
    v.gui = true
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.0.2"

end
