Vagrant.configure("2") do |config|
  config.vm.box = "centos-64-x64"

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box"
  end

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
    override.vm.network :private_network, ip: "192.168.0.2"
  end

  config.vm.synced_folder "puppet/box_modules", "/etc/puppet/modules"
  config.vm.synced_folder "puppet/manifests", "/etc/puppet/manifests"

  config.vm.provision :shell, :path => "shell/PuppetMasterInstall.sh"
end
