Vagrant.configure("2") do |config|

  config.vm.define "win2012" do |win2012|
    win2012.vm.box = "win2012r2x64"
    win2012.windows.halt_timeout = 20
    win2012.winrm.username = "vagrant"
    win2012.winrm.password = "vagrant"
    win2012.vm.guest = :windows

    win2012.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

    win2012.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "192.168.0.12"
      v.gui = true
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--usb", "off"]
    end

    win2012.vm.provision :shell, :path => "shell/InstallNet4.ps1"
    win2012.vm.provision :shell, :path => "shell/SmokeCommands.ps1"
  end

  config.vm.define "win2008" do |win2008|
    win2008.vm.box = "win2008r2x64"
    win2008.windows.halt_timeout = 20
    win2008.winrm.username = "vagrant"
    win2008.winrm.password = "vagrant"
    win2008.vm.guest = :windows

    win2008.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

    win2008.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "192.168.0.8"
      v.gui = true
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--usb", "off"]
    end

    win2008.vm.provision :shell, :path => "shell/InstallNet4.ps1"
    win2008.vm.provision :shell, :path => "shell/SmokeCommands.ps1"
  end

  config.vm.define "win2003" do |win2003|
    win2003.vm.box = "win2003x86"
    win2003.windows.halt_timeout = 20
    win2003.winrm.username = "vagrant"
    win2003.winrm.password = "vagrant"
    win2003.vm.guest = :windows

    win2003.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

    win2003.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "192.168.0.3"
      v.gui = true
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--usb", "off"]
    end

    win2003.vm.provision :shell, :path => "shell/InstallNet4.ps1"
    win2003.vm.provision :shell, :path => "shell/SmokeCommands.ps1"
  end
end
